"""Add Project model and foreign keys

Revision ID: 727ca8023a50
Revises: 0a9dea7ae937
Create Date: 2024-11-11 11:56:52.304126

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "727ca8023a50"
down_revision = "0a9dea7ae937"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("container", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "project", ["project_id"], ["id"])

    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "project", ["project_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("project_id")

    with op.batch_alter_table("container", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("project_id")

    op.drop_table("project")
    # ### end Alembic commands ###
