"""Drop project field for Container model

Revision ID: 9bed9513ee20
Revises: 727ca8023a50
Create Date: 2024-11-13 17:50:26.179537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bed9513ee20'
down_revision = '727ca8023a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_constraint('container_project_id_fkey', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('container_project_id_fkey', 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###
